### ISSUE TITLE
I don't understand several lines in ohem_detect_loss()

### ISSUE THREAD

**Issue by arieszhang1994** [princewang1994/RFCN_CoupleNet.pytorch#1]
Hi thank you for your great work.
I am reading you code of rfcn.
And don't know what does 
https://github.com/princewang1994/RFCN_CoupleNet.pytorch/blob/2498881b2ba7a1b511fe82b935ec422ca5fabe55/lib/model/rfcn/rfcn.py#L66
this line means.

From my perspective, it is a little from crossentropy.
Can you tell me more about it?

**Comment by princewang1994** [comment]
Hi, It is a manually implemented CrossEntropy from [ssd.pytorch](https://github.com/amdegroot/ssd.pytorch/blob/master/layers/modules/multibox_loss.py#L94). 
If you know about Croos Entropy, it is defined by -log(e^x/Σe^x)， and equal to CE = -log(e^x/Σe^x) = log(Σe^x/e^x) = log(Σe^x) - log(e^x) = log(Σe^x) - x， that's it:
```python
loss_c = log_sum_exp(conf_p) - conf_p.gather(1, conf_t.view(-1,1)) 
```

**Comment by princewang1994** [comment]
If there is no other issue, I'm closing this issue
